name: Bump & Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bump-and-publish:
    environment: mainnet
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup Git User
        uses: fregante/setup-git-user@v1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: |
          yarn install
      - name: Detect Version Changes
        id: detect_changes
        run: |
          bash ./bin/detect-changes
      - name: Print output
        run: echo 'Got outputs for bump_type=${{ steps.detect_changes.outputs.bump_type }}'
      - name: Bump Version
        if: ${{ steps.detect_changes.outputs.bump_type != 'none' }}
        run: |
          npm config set commit-hooks=false
          npm version ${{ steps.detect_changes.outputs.bump_type }}
          git push origin HEAD:${{ github.ref }}
      # - name: Build
      #   env:
      #     SOLANA_NETWORK: ${{ secrets.SOLANA_NETWORK }}
      #   run: |
      #     yarn generate && yarn build
      - name: Publish NPM
        uses: rxfork/npm-publish@v1
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          access: public
