name: Build and Publish

"on":
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    environment: mainnet
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: |
          yarn install
      - name: Build
        env:
          SOLANA_NETWORK: ${{ secrets.SOLANA_NETWORK }}
        run: |
          yarn generate && yarn build
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@v9.1.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          version-type: "patch"
      # - name: Publish NPM
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_ACCESS_TOKEN }}
      #     access: public
