name: Bump & Publish

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      bump_type: ${{ steps.detect_changes.outputs.bump_type }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Detect Version Changes
        id: detect_changes
        run: |
          bash ./bin/detect-changes
      - name: Setup Git User
        if: ${{ steps.detect_changes.outputs.bump_type != 'none' }}
        uses: fregante/setup-git-user@v1
      - name: Bump Version
        if: ${{ steps.detect_changes.outputs.bump_type != 'none' }}
        run: |
          npm config set commit-hooks=false
          npm version ${{ steps.detect_changes.outputs.bump_type }}
          git push --follow-tags origin HEAD:${{ github.ref }}
  publish:
    if: env.publish = 'true' && needs.bump-version.outputs.bump_type != 'none'
    environment: mainnet
    runs-on: ubuntu-latest
    needs: bump-version
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Pull
        run: |
          git pull origin HEAD
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: |
          yarn install
      - name: Generate Tokenlist
        env:
          SOLANA_NETWORK: ${{ secrets.SOLANA_NETWORK }}
        run: |
          yarn generate
      - name: Build
        run: |
          yarn build
      - name: Publish NPM
        uses: rxfork/npm-publish@v1
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          access: public
