name: Publish NPM

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    environment: mainnet
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: |
          yarn install
      - name: Generate Tokenlist
        env:
          SOLANA_NETWORK: ${{ secrets.SOLANA_NETWORK }}
        run: |
          yarn generate
      - name: Build
        run: |
          yarn build
      - name: Publish NPM
        uses: rxfork/npm-publish@v1
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          access: public
